baseURL: https://rover.kg9ov.org/
languageCode: en-us
title: KG9OV/R

disableKinds:
  # taxonomies
  - taxonomy
  - term
  # rss
  - RSS
  # sitemap.xml
  - sitemap

markup:
  goldmark:
    renderHooks:
      link:
        useEmbedded: always